string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> BLK
uint8            block_index            # <class 'int'> 
uint8            data_len               # <class 'int'> 
uint8            byte1                  # <class 'int'> 
uint8            byte2                  # <class 'int'> 
uint8            byte3                  # <class 'int'> 
uint8            byte4                  # <class 'int'> 
uint8            byte5                  # <class 'int'> 
uint8            byte6                  # <class 'int'> 
uint8            byte7                  # <class 'int'> 
uint8            byte8                  # <class 'int'> 
# Copyright © 2024 COVVI