string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caCurrentGrip
uint8            data_len               # <class 'int'> 2
Table            table                  # <enum 'Table'> 
TableIndex       table_index            # <enum 'TableIndex'> 
# Copyright © 2024 COVVI