uint8 TRIPOD      = 1
uint8 POWER       = 2
uint8 TRIGGER     = 3
uint8 PREC_OPEN   = 4
uint8 PREC_CLOSED = 5
uint8 KEY         = 6
uint8 FINGER      = 7
uint8 CYLINDER    = 8
uint8 COLUMN      = 9
uint8 RELAXED     = 10
uint8 GLOVE       = 11
uint8 TAP         = 12
uint8 GRAB        = 13
uint8 TRIPOD_OPEN = 14
uint8 GN0         = 15
uint8 GN1         = 16
uint8 GN2         = 17
uint8 GN3         = 18
uint8 GN4         = 19
uint8 GN5         = 20
uint8 value
# Copyright © 2024 COVVI