uint8 NONE              = 0
uint8 SMALL_LEFT_HAND   = 18
uint8 SMALL_RIGHT_HAND  = 19
uint8 MEDIUM_LEFT_HAND  = 20
uint8 MEDIUM_RIGHT_HAND = 21
uint8 LARGE_LEFT_HAND   = 22
uint8 LARGE_RIGHT_HAND  = 23
uint8 SYSTEM            = 33
uint8 PTEST             = 34
uint8 ELECT             = 49
uint8 SDU               = 50
uint8 PRS               = 51
uint8 ROS               = 52
uint8 RCI               = 53
uint8 ECI               = 54
uint8 WRIST             = 65
uint8 HAPTIC            = 66
uint8 value
# Copyright © 2024 COVVI