string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caDeviceIdentity
uint8            data_len               # <class 'int'> 
uint8            type                   # <class 'int'> 
bool             wrist                  # <class 'bool'> 
DeviceGlove      glove                  # <enum 'DeviceGlove'> BLACK
DeviceColour     colour                 # <enum 'DeviceColour'> 
Language         language               # <enum 'Language'> 
uint8            hw_version             # <class 'int'> 
uint8            year_of_manufacture    # <class 'int'> 
uint8            extended_warranty      # <class 'int'> 
uint8            warranty_expires_month # <class 'int'> 
uint8            warranty_expires_year  # <class 'int'> 
# Copyright © 2024 COVVI