string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> nwDeviceInfo
uint8            data_len               # <class 'int'> 
NetDevice        device_id              # <enum 'NetDevice'> 
bool             error                  # <class 'bool'> 
bool             power_on               # <class 'bool'> 
bool             connected              # <class 'bool'> 
DeviceClassType  device_class_type      # <enum 'DeviceClassType'> 
int16            serial_number          # <class 'eci.primitives.dtypes.Int16'> 
uint8            manufacturer_id        # <class 'eci.primitives.dtypes.Uint8'> 
Product          product_id             # <class 'eci.primitives.product.Product'> NONE [0]
# Copyright © 2024 COVVI