string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caDeviceProduct
uint8            data_len               # <class 'int'> 
uint8            manufacturer_id        # <class 'eci.primitives.dtypes.Uint8'> 
Product          product_id             # <class 'eci.primitives.product.Product'> NONE [0]
# Copyright © 2024 COVVI