string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caDigitStatus
uint8            data_len               # <class 'int'> 
bool             fault                  # <class 'bool'> 
bool             gripping               # <class 'bool'> 
bool             at_open                # <class 'bool'> 
bool             at_posn                # <class 'bool'> 
bool             touch                  # <class 'bool'> 
bool             stall                  # <class 'bool'> 
bool             stopped                # <class 'bool'> 
bool             active                 # <class 'bool'> 
# Copyright © 2024 COVVI