string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caDigitMove
uint8            data_len               # <class 'int'> 
uint8            position               # <class 'int'> 
Speed            speed                  # <class 'eci.primitives.speed.Speed'> 15
Percentage       power                  # <class 'eci.primitives.percentage.Percentage'> 0
Percentage       limit                  # <class 'eci.primitives.percentage.Percentage'> 0
# Copyright © 2024 COVVI