string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caDigitConfig
uint8            data_len               # <class 'int'> 
uint8            open_limit             # <class 'int'> 
uint8            close_limit            # <class 'int'> 
uint8            offset                 # <class 'int'> 
# Copyright © 2024 COVVI