string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caDigitPosn
uint8            data_len               # <class 'int'> 
Speed            speed                  # <class 'eci.primitives.speed.Speed'> 15
bool             rotate                 # <class 'bool'> 
bool             little                 # <class 'bool'> 
bool             ring                   # <class 'bool'> 
bool             middle                 # <class 'bool'> 
bool             index                  # <class 'bool'> 
bool             thumb                  # <class 'bool'> 
uint8            thumb_pos              # <class 'int'> 
uint8            index_pos              # <class 'int'> 
uint8            middle_pos             # <class 'int'> 
uint8            ring_pos               # <class 'int'> 
uint8            little_pos             # <class 'int'> 
uint8            rotate_pos             # <class 'int'> 
# Copyright © 2024 COVVI