string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caDigitPosn_all
uint8            data_len               # <class 'int'> 
uint8            thumb_pos              # <class 'int'> 
uint8            index_pos              # <class 'int'> 
uint8            middle_pos             # <class 'int'> 
uint8            ring_pos               # <class 'int'> 
uint8            little_pos             # <class 'int'> 
uint8            rotate_pos             # <class 'int'> 
# Copyright © 2024 COVVI