string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caDigitError
uint8            data_len               # <class 'int'> 
bool             position               # <class 'bool'> 
bool             limits                 # <class 'bool'> 
bool             motor                  # <class 'bool'> 
bool             hall                   # <class 'bool'> 
# Copyright © 2024 COVVI