string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caDigitTouch_all
uint8            data_len               # <class 'int'> 
uint8            thumb_touch            # <class 'int'> 
uint8            index_touch            # <class 'int'> 
uint8            middle_touch           # <class 'int'> 
uint8            ring_touch             # <class 'int'> 
uint8            little_touch           # <class 'int'> 
# Copyright © 2024 COVVI