int16            discovery_version      # <class 'eci.primitives.dtypes.Int16'> 2
int16            device_serial_number   # <class 'eci.primitives.dtypes.Int16'> 
SixOctetAddress  mac                    # <class 'eci.primitives.six_octet_address.SixOctetAddress'> 00:00:00:00:00:00
DeviceClassType  device_class_type      # <enum 'DeviceClassType'> 
uint8            manufacturer_id        # <class 'int'> 
Product          product_id             # <class 'eci.primitives.product.Product'> NONE [0]
FourOctetAddress ip                     # <class 'eci.primitives.four_octet_address.FourOctetAddress'> 0.0.0.0
FourOctetAddress subnet_mask            # <class 'eci.primitives.four_octet_address.FourOctetAddress'> 0.0.0.0
FourOctetAddress gateway                # <class 'eci.primitives.four_octet_address.FourOctetAddress'> 0.0.0.0
FourOctetAddress dns                    # <class 'eci.primitives.four_octet_address.FourOctetAddress'> 0.0.0.0
Hostname         hostname               # <class 'eci.primitives.hostname.Hostname'> 
bool             dhcp                   # <class 'bool'> 
bool             hand_comms             # <class 'bool'> 
bool             hand_power             # <class 'bool'> 
bool             client_connected       # <class 'bool'> 
FourOctetAddress client_address         # <class 'eci.primitives.four_octet_address.FourOctetAddress'> 0.0.0.0
FourOctetAddress request_source_address # <class 'eci.primitives.four_octet_address.FourOctetAddress'> 0.0.0.0
# Copyright © 2024 COVVI