string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caElectrodeValue
uint8            data_len               # <class 'int'> 
int16            voltage                # <class 'eci.primitives.dtypes.Int16'> 
# Copyright © 2024 COVVI