string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caEnvironmental
uint8            data_len               # <class 'int'> 
uint8            temperature            # <class 'int'> 
uint8            humidity               # <class 'int'> 
int16            battery_voltage        # <class 'eci.primitives.dtypes.Int16'> 
# Copyright © 2024 COVVI