string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caGripName
uint8            data_len               # <class 'int'> 
uint8            msg_num                # <class 'int'> 1
uint8            msg_total              # <class 'int'> 1
uint8            ch1                    # <class 'int'> 
uint8            ch2                    # <class 'int'> 
uint8            ch3                    # <class 'int'> 
uint8            ch4                    # <class 'int'> 
uint8            ch5                    # <class 'int'> 
uint8            ch6                    # <class 'int'> 
uint8            ch7                    # <class 'int'> 
# Copyright © 2024 COVVI