string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> 
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> nwHandPower
uint8            data_len               # <class 'int'> 
bool             enable                 # <class 'bool'> True
# Copyright © 2024 COVVI