string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caInputStatus
uint8            data_len               # <class 'int'> 
bool             supinate               # <class 'bool'> 
bool             pronate                # <class 'bool'> 
bool             back_button            # <class 'bool'> 
bool             little_tip             # <class 'bool'> 
bool             ring_tip               # <class 'bool'> 
bool             middle_tip             # <class 'bool'> 
bool             index_tip              # <class 'bool'> 
bool             thumb_tip              # <class 'bool'> 
# Copyright © 2024 COVVI