string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caMotorCurrent_all
uint8            data_len               # <class 'int'> 
uint8            thumb_current          # <class 'int'> 
uint8            index_current          # <class 'int'> 
uint8            middle_current         # <class 'int'> 
uint8            ring_current           # <class 'int'> 
uint8            little_current         # <class 'int'> 
# Copyright © 2024 COVVI