string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caMotorCurrent
uint8            data_len               # <class 'int'> 
uint8            current                # <class 'int'> 
# Copyright © 2024 COVVI