string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caMotorLimits
uint8            data_len               # <class 'int'> 
bool             hand                   # <class 'bool'> 
bool             eci                    # <class 'bool'> 
bool             ltl                    # <class 'bool'> 
bool             rng                    # <class 'bool'> 
bool             mid                    # <class 'bool'> 
bool             idx                    # <class 'bool'> 
bool             thb                    # <class 'bool'> 
uint8            thumb_derate_value     # <class 'int'> 
uint8            index_derate_value     # <class 'int'> 
uint8            middle_derate_value    # <class 'int'> 
uint8            ring_derate_value      # <class 'int'> 
uint8            little_derate_value    # <class 'int'> 
# Copyright © 2024 COVVI