string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caRealtimeCfg2
uint8            data_len               # <class 'int'> 
bool             motor_limits           # <class 'bool'> 
bool             orientation            # <class 'bool'> 
bool             environmental          # <class 'bool'> 
# Copyright © 2024 COVVI