string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caRealtimeCfg
uint8            data_len               # <class 'int'> 
bool             digit_error            # <class 'bool'> 
bool             digit_touch            # <class 'bool'> 
bool             motor_current          # <class 'bool'> 
bool             input_status           # <class 'bool'> 
bool             electrode_value        # <class 'bool'> 
bool             current_grip           # <class 'bool'> 
bool             digit_posn             # <class 'bool'> 
bool             digit_status           # <class 'bool'> 
# Copyright © 2024 COVVI