string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caSystemStatus
uint8            data_len               # <class 'int'> 
bool             bluetooth_fault        # <class 'bool'> 
bool             spi_error              # <class 'bool'> 
bool             gateway_error          # <class 'bool'> 
bool             humidity_limit         # <class 'bool'> 
bool             temperature_limit      # <class 'bool'> 
uint8            bluetooth_status       # <class 'int'> 
uint8            change_notifications   # <class 'int'> 
# Copyright © 2024 COVVI