string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> RES
MessageID        msg_id                 # <enum 'MessageID'> caUpdateDownload
uint8            data_len               # <class 'int'> 
BulkDataType     data_type              # <enum 'BulkDataType'> GRIP
GripNameIndex    grip_name_index        # <enum 'GripNameIndex'> 
UpdateStatus     update_status          # <enum 'UpdateStatus'> 
# Copyright © 2024 COVVI