; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; ----------------------------------------------------------------------
; Gravação por USB (use na 1ª vez, com o ESP no cabo):
;   pio run -e esp32doit-devkit-v1 -t upload
[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
monitor_speed = 115200

; ----------------------------------------------------------------------
; Gravação OTA pela rede (depois que o firmware com OTA já estiver no ESP):
;   pio run -e ota -t upload
[env:ota]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
upload_protocol = espota
upload_port = 192.168.5.105
upload_flags =
    --auth=Biolabeb0608
monitor_speed = 115200